# This tells Netlify where your function files are located.
[build]
  functions = "netlify.com/functions/"

# This is the correct redirect rule for a Single-Page App.
# It serves your main app on any path, BUT it ignores paths
# that are for Netlify Functions, which is what we want.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Path = {"^/(?!.netlify).*$"}}